apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rhdc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-rhdc@sha256:808fdb9443c1af106452aafc67bb8fa34ced222772e798c1c50ce0bec0ed7bd7
        name: my-nodejs
        resources: {}
status: {}
